HAI 1.2
I HAS A I,VISIBLE "Enter Number::"!
GIMMEH I,I IS NOW A NUMBR

I HAS A T ITZ I
I HAS A REV ITZ 0
I HAS A REM
I HAS A E ITZ "a Palindrome"
I HAS A L ITZ 0
IM IN YR LOOP UPPIN YR L TIL BOTH SAEM T AN 0
    REM R MOD OF T AN 10 
    REV R SUM OF PRODUKT OF REV AN 10 AN REM
    T R QUOSHUNT OF T AN 10
IM OUTTA YR LOOP
BOTH SAEM I AN REV
VISIBLE SMOOSH I " is " MKAY!
O RLY?,YA RLY,VISIBLE "" E,NO WAI,VISIBLE "Not " E,OIC
KTHXBYE